FROM nginx:alpine

COPY /var/jenkins_home/workspace/Flutter/build/app/outputs/flutter-apk/app-release.apk /usr/share/nginx/html/app-release.apk

RUN echo '<h1>Tester Build</h1><a href="app-release.apk">Download APK</a>' \
> /usr/share/nginx/html/index.html
